### ISSUE TITLE
FBRB compression incompatible with Battlefield Bad Company (PS3)

### ISSUE THREAD

**Issue by Sandvichero** [HeicoDev/FBOneTools#6]
When recompressing and then replacing .fbrb files from Bad Company on ps3 it crashes on start, even with no modifications done to contents of the archive. Also, changing the compression in the python script had no effect. 

This is the unmodified .fbrb file from the game.
[FBRB.zip](https://github.com/HeicoDev/FBOneTools/files/5579748/FBRB.zip)

**Comment by HeicoDev** [comment]
Fixed
